export const SET_TODOS_TYPE = 'SET_TODOS_TYPE';
export const UPDATE_TODO_TYPE = 'UPDATE_TODO_TYPE';
export const GET_TODO_TYPE = 'GET_TODO_TYPE';
export const DELETE_TODO_TYPE = 'DELETE_TODO_TYPE';
export const ADD_TODO_TYPE = 'ADD_TODO_TYPE'